# fly.toml file generated for lions on 2022-08-01T11:55:58+02:00

app = "lions"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  # Secrets:
  # * LITESTREAM_ACCESS_KEY_ID
  # * LITESTREAM_SECRET_ACCESS_KEY
  # * LIONS_SCRYPT_SIGNER_KEY
  # * LIONS_SCRYPT_SALT_SEP
  # * LIONS_AWS_SES_ACCESS_KEY
  # * LIONS_AWS_SES_SECRET_ACCESS_KEY
  LITESTREAM_BUCKET = "lions-achern-litestream-replica-1"
  LITESTREAM_RESTORE_PATH = "fly-members-1"
  LITESTREAM_REPLICATE_PATH = "fly-members-1"
  LIONS_SQLITE_PATH = "/usr/local/lib/sqlite/sqlite.db"
  LIONS_LOG_LEVEL = "info"
  LIONS_ENV = "production"
  LIONS_SERVER_LISTEN_ADDR = "127.0.0.1"
  LIONS_SESSION_KEY_FILE = "/usr/local/lib/sqlite/session.aes"

[mounts]
  source = "data"
  destination = "/usr/local/lib"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
